spring.application.name=spring-security

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://localhost/springsecurity
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=localhost
spring.mail.port=25
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

jwt.secret=Q+phl38GIdHrDug1Cz1biJyxquRlENfef4HK+P6Nko8=

google.recaptcha.site=6LftOIksAAAAAB4UcpeRDKVQrJSn5tuu8l95r6re
google.recaptcha.secret=6LftOIksAAAAAItXOI0Yo8m4nvBS4r93Xos8fqOx